name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

permissions:
  contents: write  # ✅ Allows Actions to push to gh-pages branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents credential issues

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Match your Angular version

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --output-path=dist --base-href=/Angular_Projects/browser/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Uses GitHub's built-in token
          branch: gh-pages  # Target branch
          folder: dist  # Deploy this folder
